### ISSUE TITLE
Can the required libstdc++ version be lowered?

### ISSUE THREAD

**Issue by probonopd** [mmatyas/openblok#13]
Trying to run the AppImage on Ubuntu 14.04 trusty, getting `usr/bin/openblok: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /run/firejail/appimage/.appimage-7955/usr/bin/openblok)`.

Can the required libstdc++ version be lowered?
As is, this prevents from being included in the [AppImageHub](https://github.com/AppImage/AppImageHub) central directory of available AppImages.

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266227555#L554

**Comment by mmatyas** [comment]
OpenBlok uses some C++11/14 features, which were first implemented in GCC 4.9.0 (libstdc++ 3.4.20), eg. `std::regex` and `std::make_unique`. Some functions work differently (eg simply `return false` in 4.8), or have a different syntax between the two versions. I'm not sure if it'd be possible making it work with earlier libstdc++, without rewriting some parts of the code or adding new dependencies.

On the other hand I wonder if creating a static build would work? That is, building on Ubuntu 14.04 but using GCC 4.9 from the Ubuntu dev PPA.

**Comment by mmatyas** [comment]
Hm no, static build probably won't work either...

**Comment by probonopd** [comment]
Are these C++11/14 features _really_ needed?

**Comment by mmatyas** [comment]
Yes, but with some workaround I think I can add 4.8 compatibility. The main problem is the regex library, but I can add a wrapper layer that'd use eg. Boost.Regex on 4.8. I use some minor C++14 features like `std::make_unique`, but likely those can be replaced as well.

**Comment by mmatyas** [comment]
I've managed to make it work only with C++11, using Boost.Regex on 14.04. Unfortunately Boost also causes the generated AppImages to be more than twice as big, around 20 MB. It seems to depend on the ICU Unicode libraries, that are almost 30 MB uncompressed on their own.

**Comment by probonopd** [comment]
I think that's an acceptable price to pay for now.

**Comment by mmatyas** [comment]
Ok, patches merged, and I'll likely set up a `continuous` branch later as well. Will keep you updated.

**Comment by mmatyas** [comment]
Ok, there's now a continuous release, updated on every commit.

**Comment by probonopd** [comment]
Thank you, added to https://github.com/AppImage/AppImageHub/commit/0cd5f424add73c906ca1c3066b718e50f2d93b30.

Even with update information, cool!
