### ISSUE TITLE
Clearing a line crashes the game

### ISSUE THREAD

**Issue by bleonard252** [mmatyas/openblok#17]
Whenever I try to clear a line, the game crashes. Help?

**Comment by mmatyas** [comment]
Interesting, could you tell more details? What kind of system you're using, which version you've downloaded? Does the problem occur every time?

**Comment by bleonard252** [comment]
It once cleared lines, but now it does not. I am running it on Raspbian on a Pi 3, and I "built from source" a few days ago. Yes, it occurs every time.

**Comment by mmatyas** [comment]
I've just built from source too on a Pi 3, running Raspbian Jessie, but everything works fine for me. Perhaps there's something else that differs? What kind of system do you run on the board (eg. Raspbian Stretch, Ubuntu Core 16, etc.)? Do you use something over it (eg. RetroPie)? Do you see something interesting on the console output?

**Comment by bleonard252** [comment]
Yes, I installed it and use it with RetroPie (latest version AFAIK). I installed it via that RetroPie Setup thing. It's the latest version of everything, to my knowledge.

**Comment by HerbFargus** [comment]
can't reproduce. running on RetroPie 4.4, Pi 3B.

**Comment by bleonard252** [comment]
Maybe resetting options might help? I remember changing something, like the rotation style, then it not working.

**Comment by bleonard252** [comment]
Uninstalling and reinstalling does the trick.
