### ISSUE TITLE
Team mode?

### ISSUE THREAD

**Issue by felleg** [mmatyas/openblok#22]
More a question/suggestion than a bug :)

I'm playing this game at lunch with co-workers and there are skill imbalances in the players. I was wondering how feasible it would be to implement a team mode. 

The way we imagined it would be that when garbage is sent to other players, instead of being randomized across all other players, it is randomized across players from a random opposite team (maximum of 3 teams, or free-for-all, because there are 4 players).

This would probably require the addition of a team selection screen or menu, we're not familiar with the source code so we have no idea how hard it would be to implement! :stuck_out_tongue: 

Cheers and thanks for this great game!

**Comment by mmatyas** [comment]
That's a good idea! It shouldn't be too hard to implement, I just have to find some time to work on it (the bane of having too many side projects).

**Comment by felleg** [comment]
Good to know! :D I will not hold my breath, but I'm excited.

**Comment by mmatyas** [comment]
Ok, team mode is now available in the latest version! Give it a try and feel free to report any issues you run into.

**Comment by PinkDev1** [comment]
@mmatyas or @felleg, I suggest either of you close this "issue", as the feature requested has been added.

**Comment by felleg** [comment]
Thanks so much for taking the time to at this feature! I'm excited to try it out.
