### ISSUE TITLE
Player 4 cannot select team in team mode

### ISSUE THREAD

**Issue by felleg** [mmatyas/openblok#24]
Running Openblok 0.8.0 on RetroPie, when player 4 enters the team selection screen, everything "freezes". In other words, no one can change teams anymore.

As a result, player 4 is always alone in their team, there is no way to make a 3 vs 1 match.

Is anyone else able to replicate this bug?

**Comment by mmatyas** [comment]
Yeah that might not have been properly tested (hard to control 4 controllers at once :) ). This should be fixed now in [0.8.1](https://github.com/mmatyas/openblok/releases/tag/v0.8.1), thanks for the report!

**Comment by felleg** [comment]
You are an absolute king. Can't wait to test! Will close for now, and reopen if I face any issues :)
