### ISSUE TITLE
problem with USB gamepad on retropie

### ISSUE THREAD

**Issue by alexandremarcil** [mmatyas/openblok#26]
I just purchased two additional USB gamepad for 4 player games, which are these controllers:
https://www.amazon.com/Classic-Controller-Gamepad-kiwitat%C3%A1-Joysticks/dp/B01JYGYAUG/
They work fine on the retropie (recognized as "USB gamepad").  But in OpenBlok, it is recognized as a retrolink saturn classic controller.  I have used the input menu to map the controls but there is still a weird issue.  As soon as I move left, all blocks start moving left continually.  It's impossible to play with these controllers.  Is there a way to manually select which controller I am using?  Or correct this continuous moving left behavior?  Thanks!
![menu](https://user-images.githubusercontent.com/33580707/69195689-691f9280-0afa-11ea-8a14-6c43d91b08b1.png)
![left](https://user-images.githubusercontent.com/33580707/69195690-691f9280-0afa-11ea-8658-a75b9461cec9.png)

**Comment by mmatyas** [comment]
Yes, unfortunately some controllers don't work really well at the moment (I have a similar controller producing the same issue). I'll see if it can be improved.

**Comment by ParadoxGBB** [comment]
I'm hitting this as well, for both of my pads of different types --- issue has existed for a long time and persisted on upgrades from a 3B to a Raspberry Pi 4 from Stretch to Buster. Really hoping this can be addressed!

**Comment by mmatyas** [comment]
I've just updated the list of recognized gamepads, could you check the latest version?

**Comment by mmatyas** [comment]
I guess this can be closed then.

**Comment by ParadoxGBB** [comment]
@mmatyas, could you do another refresh? My 8BitDo zero 2 has this issue (but the others remain fixed).

**Comment by mmatyas** [comment]
Will look into it!

**Comment by mmatyas** [comment]
Ok, there's a new update out!

**Comment by ParadoxGBB** [comment]
Thanks so much! I updated my Pi4 and my Pi02W, and both are much better with regard to right/left. The 8BitDo Zero 2 and the native RetroFlag GPi case's pad has no button mapped to the pause menu, though, but if you need to stop you can sink the game I suppose. It's playable, which is an improvement to before.

A lot of ports out there are old DOS games that allow custom joystick calibrations... maybe that would help futureproof OpenBlok? It seems odd that the database is staticly referenced.

**Comment by mmatyas** [comment]
The problem with customizing joysticks is that in practice if the game doesn't detect the key press, you can't remap it either :/ But perhaps in the future there could be some sort of configuration.

**Comment by ParadoxGBB** [comment]
Apologies for pinging this issue yet again, but can we have yet another refresh? I'm doing some testing on Raspberry Pi OS Bullseye 64-bit and I'm seeing almost exactly the same symptoms back in 11/19/2019 --- left button once hit glues to the left. Mapping used to be b to rotate, now it's x, etc.

Thanks so much for this program, it's a lot of fun to play.

**Comment by mmatyas** [comment]
Ok, updated the gamepad list, hope it helps!

**Comment by ParadoxGBB** [comment]
@mmatyas Thanks, but it looks like that didn't help with my config. 

At some point I might have time to try this on Bullseye 32 just to help narrow down a bit but it seems like this might not be usable in the current state, oh well.
