### ISSUE TITLE
Clearing lines with Sonic Drop on causes crash

### ISSUE THREAD

**Issue by Nocosix** [mmatyas/openblok#28]
When trying to play with Sonic Drop on, the game will randomly segfault when trying to line clear. It occurs frequently enough that I can't finish a game of sprint.
This happened to me on v0.7.0 on the Raspberry Pi 3 and 4, and also on an Arch Linux desktop built from the latest commit.

**Comment by mmatyas** [comment]
Ok, this should be fixed now in the latest release, thanks! (But feel free to report if the problem still occurs.)

**Comment by PinkDev1** [comment]
I'm happy to say that as of build v0.8.2+ea9a457 I am not able to replicate the issue :)
I've played a Sprint game (2:41) and a Marathon game (4:30~) with Sonic Drop activated and no errors showed up. (Apart from the errors displayed on the cmd mentioned on issue #30 )

**Comment by mmatyas** [comment]
:+1:
