### ISSUE TITLE
Localisation Support

### ISSUE THREAD

**Issue by SkoricIT** [mmatyas/openblok#38]
Is there any possibility to include localisation support?
I would love to give this to my German speaking uncle who uses windows.

Also, I would love to contribute that feature, but would like to know how you would prefer this to be implemented.

**Comment by mmatyas** [comment]
Hi, at the moment all texts are part of the source code, but it could be possible to implement such feature. I heard good things about GNU Gettext for example, maybe it could be set up for this project too.

On the other hand, there's not that much text outside the settings menu, and that too mainly consists of terms like "Ultra", "T-Spin", etc. If you just wish to teach the usage of the game, perhaps some translated screenshots might work? Of course, if you'd like to work on this, contributions are welcome!

**Comment by SkoricIT** [comment]
I have implemented the functionality and have created pull request #39

**Comment by mmatyas** [comment]
Closed by #39 and #43.
