### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by dantchapman** [mmatyas/openblok#42]
More a q question than an issue. Do you plan to support OSX 'out of the box'
I have managed to build on OSX with the following:
Installed SDL2 from brew
fixed sdl mixer to include mp3 (https://github.com/veandco/go-sdl2/issues/299)
I also updated the includes, removing 'SDL2/'  on the following :
src/system/Paths.cpp
src/system/sdl/SDLFont.cpp
src/system/sdl/SDLGraphicsContext.cpp

There remains a couple of 'flickers' on the screen after playing for a while, bit otherwise completely playable.

**Comment by mmatyas** [comment]
Hi, I don't have any Mac devices, so I can't really develop or test things there. However SDL2 is fairly portable, so the build itself should work in the future too.

**Comment by mmatyas** [comment]
I guess this can be closed.

**Comment by dantchapman** [comment]
That’s fine - just info for anyone trying to build on OS X
