### ISSUE TITLE
Was an Android Release ever planned?

### ISSUE THREAD

**Issue by SecularSteve** [mmatyas/openblok#53]
I mean, it seems almost logical at this point. With a unique control system/overlay used only for that build (if a touchscreen is detected).

Obviously, a few of the MP modes will need a mass re-tooling because not all screens are big enough for multiple players.

I can design the new icon if you want me to (both Mobile, and TV variations).

It doesn't even have to start off on the Play Store immediately. Just test-market it as a direct APK like Pegasus or something.

But that's purely a suggestion. It's your project, and you do what you want with it.

**Comment by mmatyas** [comment]
Well, if there's a lesson learned with Pegasus, it's that I don't have the hardware, time and energy to properly support an Android release :laughing: 
If you'd like to work on this, feel free to, but I'm not planning a port at the moment.

**Comment by SecularSteve** [comment]
Thank you for the answer, have a nice day...

**Comment by mmatyas** [comment]
I suppose this can be closed.
