### ISSUE TITLE
Installation inquiry

### ISSUE THREAD

**Issue by trolololo-haha** [mmatyas/openblok#57]
Hi, thank you for developing the game :)

This is not necessary an issue/bug, though I would like to ask you to help with a installation guide on a steam deck?
Installing this type of application/games, also works, as with after several tries nothing really worked, but it seems I'm not really familiar with Linux OS.

Thank you in advance

**Comment by mmatyas** [comment]
Hi! I'm afraid don't have a Steam Deck, so I'm not sure how things work there. On PC, you can download the Linux AppImage version, right click -> _Properties_ -> _Allow this file to run as a program_, then double click on the file to start the game.

**Comment by trolololo-haha** [comment]
Thank you, the used OS is based on Arch Linux distribution with KDE Plasma 5 (if it helps).

I have downloaded the file, but I couldn't find this option "Allow this file to run as a program". The closest thing, right click -> Properties -> Permissions -> I have enabled the "is executable" checkbox. After that I have tried double clicking, but it had no effect, nothing loaded.

**Comment by mmatyas** [comment]
Hm, probably some dependencies are incompatible with the Deck, but not sure it that's fixable without rebuilding the game from source. You could try launching the appimage from the command line, to see if it prints any error messages (there should be a terminal on the Deck, but not sure how you can access that).

**Comment by trolololo-haha** [comment]
Thank you, yes, there is a terminal, I will give it a try and follow up, I assume following this guide: https://docs.appimage.org/introduction/quickstart.html#using-the-terminal

**Comment by trolololo-haha** [comment]
Hi, after trying to install using the terminal I got the following error:
openblok: error while loading shared libraries: libpulsecommon-13.99.so: cannot open shared object file: No such file or directory

Upon checking the lib folders (as I couldn't find how to check if there is a library installed and which version is installed), more specifically this directory: rootfs/lib/pulseaudio, I have found the following files: libpulsecommon-16.1.so and libpulsedsp.so

Should I install the following library: libpulsecommon-13.99.so ? If yes, how can it be done?

**Comment by mmatyas** [comment]
Thanks! It seems the AppImage was missing support for newer audio drivers. I'll update the release.

**Comment by mmatyas** [comment]
Ok! Give this one a try: https://github.com/mmatyas/openblok/releases/tag/v0.8.6

**Comment by trolololo-haha** [comment]
Thank you for the new release and for solving the problem, the game can be launched successfully now.

I'm closing this issue as it's fixed.
