### ISSUE TITLE
"Failed to Loads Gamepad mapping; Invalid RWops"

### ISSUE THREAD

**Issue by DrWholian** [mmatyas/openblok#62]
Error message is the thread title. During gameplay, directional input seems to be sporadically ignored at random intervals.

I'm running a PS4 controller emulated as Xbox 360 input through Steam in Win10.

Any idea how to solve this? Thanks in advance.

**Comment by mmatyas** [comment]
Hm, it sounds as if the game didn't find the file at the given location (the error should say the path it checks), or could not open it for some reason (eg. some permission issue or network drive). This isn't a critical issue, an Xbox layout will probably have correct defaults out of the box; I wonder if it's related to Steam perhaps? Have you tried running outside of it?

**Comment by mmatyas** [comment]
Ok, this should be fixed in the latest version, could you check if it still happens?

**Comment by DrWholian** [comment]
At first glance, it appears to be fixed! I'll try it some more with my siblings and see if it creeps back up.

**Comment by mmatyas** [comment]
I'll close this for now, but feel free to reopen it the issue still occurs.
