### ISSUE TITLE
Errors when build project with Cmake at Windows

### ISSUE THREAD

**Issue by AntonieS** [mmatyas/openblok#69]
CMake Error at thirdparty/CMakeLists.txt:6 (add_subdirectory):
  The source directory

   ../openblok-master/thirdparty/libSDL2pp

  does not contain a CMakeLists.txt file.

CMake Error at ../cmake-3.29.2/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Failed to find Gettext libintl (missing: Intl_LIBRARY Intl_INCLUDE_DIR)
Call Stack (most recent call first):
  ../cmake-3.29.2/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
 ../cmake-3.29.2/share/cmake-3.29/Modules/FindIntl.cmake:161 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/system/CMakeLists.txt:62 (find_package)

**Comment by mmatyas** [comment]
Hi! You seem to have two issues:

- You didn't clone the submodules of the repository, so the dependencies are missing. Take a look in your Git client's documentation about how to do a recursive clone.
- Gettext is missing. This is used for localization, and you have to build it for your system. Alternatively, you can set the CMake property `ENABLE_LOCALES=OFF` to build without localization suppport.

**Comment by AntonieS** [comment]
Thanks for help!

Now another trouble:

CMake Error at ../cmake-3.29.2/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2MAIN_LIBRARY
  SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  ../cmake-3.29.2/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  thirdparty/libSDL2pp/cmake/FindSDL2.cmake:20 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  thirdparty/libSDL2pp/CMakeLists.txt:29 (FIND_PACKAGE)

Configuring incomplete, errors occurred!


I have SDL2 sources but where to place them in project?

**Comment by mmatyas** [comment]
Ah, if you don't have the SDL libraries, you have to build them separately, and place them somewhere CMake can find them. If you're on windows, you can alternatively use the official SDL builds for your compiler from their official site. It _seems_ you might be using some Linux distro though, perhaps you could install them from your package manager too?

**Comment by AntonieS** [comment]
I use Windows and Visual Studio 2019, CMake 3.29.2.
Set paths in CMake toSDL2-devel-2.30.3-VC - and its OK but:

Checking for experimental/optional header: no
libSDL2pp 0.16.0 bundled build
|
|  Build type:       release
|  Tests:            do not build
|  Install:          portable, default install to C:/Program Files (x86)/openblok
|  - runtime dir:    .
|  - data dir:       ./data
|  - localization:   yes
|
Configuring done (0.1s)
Generating done (0.0s)

And no results.

**Comment by mmatyas** [comment]
Well, this slice of the log seems to indicate success?

**Comment by AntonieS** [comment]
Yes, but where is build? %)))
Cannot find it. %)))

**Comment by mmatyas** [comment]
CMake generates project files for compilers, but does not build anything by itself. If you are using Visual Studio, you should now have Visual Studio project files you can open. You can take a look in the CMake documentation if you are unfamiliar with CMake projects.

**Comment by mmatyas** [comment]
I suppose this can be closed.
